[book]
title = "Seqlings"
authors = ["Ed Sweeney"]
description = "Documentation for seqlings"
src = "docs"
language = "en"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/navicore/seqlings"
edit-url-template = "https://github.com/navicore/seqlings/edit/main/docs/{path}"
site-url = "/seqlings/"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
boost-hierarchy = 2
